---
- name: Show info about env
  debug:
    msg: "This host is in {{ env }} environment!"

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: Enable puma
  systemd:
    name: puma
    enabled: yes
