---
- name: Initial provisioning of db base image.
  hosts: all
  become: yes

  tasks:
    - name: Add apt-key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add mongo repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: latest

    - name: Enable service
      systemd:
        name: mongod
        enabled: yes